export const queryKeys = {
  authMe: () => ["auth", "me"] as const,
  accounts: () => ["accounts"] as const,
  categories: () => ["categories"] as const,
  trips: () => ["trips"] as const,
  // Prefix keys (…All) exist so cache invalidations can match every parameterized variant
  // without duplicating the string literals.
  transactionsAll: () => ["transactions"] as const,
  transactionById: (id: string) => ["transactions", id] as const,
  transactionsSearchAll: () => ["transactions-search"] as const,
  transactionsSearch: (query?: Record<string, unknown>) => ["transactions-search", query ?? {}] as const,
  transactionsSummaryAll: () => ["transactions-summary"] as const,
  transactionsSummary: (query?: Record<string, unknown>) => ["transactions-summary", query ?? {}] as const,
  transactionsFacetsAll: () => ["transactions-facets"] as const,
  transactionsFacets: (query?: Record<string, unknown>) => ["transactions-facets", query ?? {}] as const,
  reportsCashflowSeriesAll: () => ["reports-cashflow-series"] as const,
  reportsCashflowSeries: (query?: Record<string, unknown>) => ["reports-cashflow-series", query ?? {}] as const,
  reportsCategorySeriesAll: () => ["reports-category-series"] as const,
  reportsCategorySeries: (query?: Record<string, unknown>) => ["reports-category-series", query ?? {}] as const,
  reportsPortfolioBalanceSeriesAll: () => ["reports-portfolio-balance-series"] as const,
  reportsPortfolioBalanceSeries: (query?: Record<string, unknown>) => ["reports-portfolio-balance-series", query ?? {}] as const,
  reportsComparisonAll: () => ["reports-comparison"] as const,
  reportsComparison: (query?: Record<string, unknown>) => ["reports-comparison", query ?? {}] as const,
  appInfo: () => ["app-info"] as const,
  settings: () => ["settings"] as const,
  emailConnections: () => ["email-connections"] as const,
  emailImportRules: () => ["email-import-rules"] as const,
  emailImportItemsAll: () => ["email-import-items"] as const,
  emailImportItems: (query?: Record<string, unknown>) => ["email-import-items", query ?? {}] as const,
  emailImportStatus: () => ["email-import-status"] as const,
}
