// <auto-generated />
using System;
using FlametteMoney.Web.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlametteMoney.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211005949_ExpandCategories")]
    partial class ExpandCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Color = "#FF7043",
                            Icon = "cart",
                            Name = "Groceries",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa9c2c"),
                            Color = "#66BB6A",
                            Icon = "apple",
                            Name = "Fruits & Vegetables",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1001"),
                            Color = "#FFEE58",
                            Icon = "egg",
                            Name = "Dairy & Eggs",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1002"),
                            Color = "#EF5350",
                            Icon = "meat",
                            Name = "Meat & Fish",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1003"),
                            Color = "#D4A373",
                            Icon = "bread",
                            Name = "Bread & Bakery",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1004"),
                            Color = "#CE93D8",
                            Icon = "candy",
                            Name = "Sweets & Snacks",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1005"),
                            Color = "#4FC3F7",
                            Icon = "drink",
                            Name = "Beverages",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1006"),
                            Color = "#AB47BC",
                            Icon = "wine",
                            Name = "Alcohol",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1007"),
                            Color = "#80DEEA",
                            Icon = "frozen",
                            Name = "Frozen Food",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa1008"),
                            Color = "#FFA726",
                            Icon = "can",
                            Name = "Canned & Dry Goods",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c7f1c2"),
                            Color = "#EC407A",
                            Icon = "restaurant",
                            Name = "Restaurants",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c72001"),
                            Color = "#F48FB1",
                            Icon = "table",
                            Name = "Dine-in",
                            ParentId = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c7f1c2"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c72002"),
                            Color = "#FF8A65",
                            Icon = "delivery",
                            Name = "Delivery",
                            ParentId = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c7f1c2"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c72003"),
                            Color = "#FFB74D",
                            Icon = "bag",
                            Name = "Takeaway",
                            ParentId = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c7f1c2"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c72004"),
                            Color = "#A1887F",
                            Icon = "coffee",
                            Name = "Cafes",
                            ParentId = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c7f1c2"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c72005"),
                            Color = "#FFD54F",
                            Icon = "tip",
                            Name = "Tips",
                            ParentId = new Guid("b2a2d8d8-2e4b-5b1c-a41b-6f75d9c7f1c2"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Color = "#8D6E63",
                            Icon = "home",
                            Name = "Housing",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d30001"),
                            Color = "#A1887F",
                            Icon = "key",
                            Name = "Rent",
                            ParentId = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d30002"),
                            Color = "#FFB300",
                            Icon = "bolt",
                            Name = "Utilities",
                            ParentId = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d30003"),
                            Color = "#29B6F6",
                            Icon = "wifi",
                            Name = "Internet",
                            ParentId = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d30004"),
                            Color = "#78909C",
                            Icon = "wrench",
                            Name = "Maintenance",
                            ParentId = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d30005"),
                            Color = "#7E57C2",
                            Icon = "shield",
                            Name = "Insurance",
                            ParentId = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Color = "#42A5F5",
                            Icon = "car",
                            Name = "Transport",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b0001"),
                            Color = "#EF5350",
                            Icon = "fuel",
                            Name = "Fuel",
                            ParentId = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b0002"),
                            Color = "#26A69A",
                            Icon = "bus",
                            Name = "Public Transit",
                            ParentId = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b0003"),
                            Color = "#FFA726",
                            Icon = "taxi",
                            Name = "Taxi & Ride",
                            ParentId = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b0004"),
                            Color = "#78909C",
                            Icon = "park",
                            Name = "Parking",
                            ParentId = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b0005"),
                            Color = "#5C6BC0",
                            Icon = "wrench",
                            Name = "Car Service",
                            ParentId = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c3b3e9e9-3f5c-6c2d-b52c-7086ead802d3"),
                            Color = "#AB47BC",
                            Icon = "bag",
                            Name = "Shopping",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c3b3e9e9-3f5c-6c2d-b52c-708600080001"),
                            Color = "#EC407A",
                            Icon = "shirt",
                            Name = "Clothes",
                            ParentId = new Guid("c3b3e9e9-3f5c-6c2d-b52c-7086ead802d3"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c3b3e9e9-3f5c-6c2d-b52c-708600080002"),
                            Color = "#42A5F5",
                            Icon = "device",
                            Name = "Electronics",
                            ParentId = new Guid("c3b3e9e9-3f5c-6c2d-b52c-7086ead802d3"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c3b3e9e9-3f5c-6c2d-b52c-708600080003"),
                            Color = "#8D6E63",
                            Icon = "shoe",
                            Name = "Shoes",
                            ParentId = new Guid("c3b3e9e9-3f5c-6c2d-b52c-7086ead802d3"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c3b3e9e9-3f5c-6c2d-b52c-708600080004"),
                            Color = "#FFD54F",
                            Icon = "gem",
                            Name = "Accessories",
                            ParentId = new Guid("c3b3e9e9-3f5c-6c2d-b52c-7086ead802d3"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c3b3e9e9-3f5c-6c2d-b52c-708600080005"),
                            Color = "#66BB6A",
                            Icon = "book",
                            Name = "Books",
                            ParentId = new Guid("c3b3e9e9-3f5c-6c2d-b52c-7086ead802d3"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d4c4fafa-4064-7d3e-c63d-8197fb1903e4"),
                            Color = "#26A69A",
                            Icon = "house",
                            Name = "Household",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d4c4fafa-4064-7d3e-c63d-819700190001"),
                            Color = "#4FC3F7",
                            Icon = "spray",
                            Name = "Cleaning Supplies",
                            ParentId = new Guid("d4c4fafa-4064-7d3e-c63d-8197fb1903e4"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d4c4fafa-4064-7d3e-c63d-819700190002"),
                            Color = "#8D6E63",
                            Icon = "chair",
                            Name = "Furniture",
                            ParentId = new Guid("d4c4fafa-4064-7d3e-c63d-8197fb1903e4"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d4c4fafa-4064-7d3e-c63d-819700190003"),
                            Color = "#66BB6A",
                            Icon = "plant",
                            Name = "Garden",
                            ParentId = new Guid("d4c4fafa-4064-7d3e-c63d-8197fb1903e4"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d4c4fafa-4064-7d3e-c63d-819700190004"),
                            Color = "#FF7043",
                            Icon = "pan",
                            Name = "Kitchen Supplies",
                            ParentId = new Guid("d4c4fafa-4064-7d3e-c63d-8197fb1903e4"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a04f5"),
                            Color = "#EF5350",
                            Icon = "heart",
                            Name = "Health & Fitness",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a0001"),
                            Color = "#E57373",
                            Icon = "pill",
                            Name = "Pharmacy",
                            ParentId = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a04f5"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a0002"),
                            Color = "#F48FB1",
                            Icon = "medkit",
                            Name = "Doctor",
                            ParentId = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a04f5"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a0003"),
                            Color = "#FF7043",
                            Icon = "gym",
                            Name = "Gym",
                            ParentId = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a04f5"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a0004"),
                            Color = "#42A5F5",
                            Icon = "sport",
                            Name = "Sports",
                            ParentId = new Guid("e5d50b0b-5175-8e4f-d74e-92a80c2a04f5"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b15a6"),
                            Color = "#FFCA28",
                            Icon = "star",
                            Name = "Entertainment",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b0001"),
                            Color = "#AB47BC",
                            Icon = "film",
                            Name = "Movies & Cinema",
                            ParentId = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b15a6"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b0002"),
                            Color = "#5C6BC0",
                            Icon = "game",
                            Name = "Games",
                            ParentId = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b15a6"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b0003"),
                            Color = "#EC407A",
                            Icon = "music",
                            Name = "Concerts & Events",
                            ParentId = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b15a6"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b0004"),
                            Color = "#66BB6A",
                            Icon = "hobby",
                            Name = "Hobbies",
                            ParentId = new Guid("f6e61c1c-6286-9f50-e85f-a3b91d3b15a6"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c26b7"),
                            Color = "#5C6BC0",
                            Icon = "school",
                            Name = "Education",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c0001"),
                            Color = "#7E57C2",
                            Icon = "course",
                            Name = "Courses",
                            ParentId = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c26b7"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c0002"),
                            Color = "#8D6E63",
                            Icon = "book",
                            Name = "Textbooks",
                            ParentId = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c26b7"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c0003"),
                            Color = "#FFA726",
                            Icon = "pen",
                            Name = "Stationery",
                            ParentId = new Guid("a7f72d2d-7397-a061-f960-b4ca2e4c26b7"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d37c8"),
                            Color = "#7E57C2",
                            Icon = "repeat",
                            Name = "Subscriptions",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d0001"),
                            Color = "#AB47BC",
                            Icon = "play",
                            Name = "Streaming",
                            ParentId = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d37c8"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d0002"),
                            Color = "#42A5F5",
                            Icon = "app",
                            Name = "Software",
                            ParentId = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d37c8"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d0003"),
                            Color = "#FFD54F",
                            Icon = "card",
                            Name = "Memberships",
                            ParentId = new Guid("b8083e3e-84a8-b172-0a71-c5db3f5d37c8"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c9194f4f-95b9-c283-1b82-d6ec4060a8d9"),
                            Color = "#F48FB1",
                            Icon = "self",
                            Name = "Personal Care",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c9194f4f-95b9-c283-1b82-d6ec40600001"),
                            Color = "#CE93D8",
                            Icon = "scissor",
                            Name = "Haircut",
                            ParentId = new Guid("c9194f4f-95b9-c283-1b82-d6ec4060a8d9"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c9194f4f-95b9-c283-1b82-d6ec40600002"),
                            Color = "#EC407A",
                            Icon = "beauty",
                            Name = "Cosmetics",
                            ParentId = new Guid("c9194f4f-95b9-c283-1b82-d6ec4060a8d9"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("da2a5050-a6ca-d394-2c93-e7fd5171b9ea"),
                            Color = "#EC407A",
                            Icon = "gift",
                            Name = "Gifts & Donations",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("da2a5050-a6ca-d394-2c93-e7fd51710001"),
                            Color = "#F48FB1",
                            Icon = "present",
                            Name = "Gifts",
                            ParentId = new Guid("da2a5050-a6ca-d394-2c93-e7fd5171b9ea"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("da2a5050-a6ca-d394-2c93-e7fd51710002"),
                            Color = "#66BB6A",
                            Icon = "heart",
                            Name = "Charity",
                            ParentId = new Guid("da2a5050-a6ca-d394-2c93-e7fd5171b9ea"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eb3b6161-b7db-e4a5-3da4-f80e6282cafb"),
                            Color = "#26C6DA",
                            Icon = "plane",
                            Name = "Travel",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eb3b6161-b7db-e4a5-3da4-f80e62820001"),
                            Color = "#29B6F6",
                            Icon = "plane",
                            Name = "Flights",
                            ParentId = new Guid("eb3b6161-b7db-e4a5-3da4-f80e6282cafb"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eb3b6161-b7db-e4a5-3da4-f80e62820002"),
                            Color = "#8D6E63",
                            Icon = "bed",
                            Name = "Hotels",
                            ParentId = new Guid("eb3b6161-b7db-e4a5-3da4-f80e6282cafb"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eb3b6161-b7db-e4a5-3da4-f80e62820003"),
                            Color = "#42A5F5",
                            Icon = "car",
                            Name = "Car Rental",
                            ParentId = new Guid("eb3b6161-b7db-e4a5-3da4-f80e6282cafb"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eb3b6161-b7db-e4a5-3da4-f80e62820004"),
                            Color = "#FFCA28",
                            Icon = "map",
                            Name = "Activities",
                            ParentId = new Guid("eb3b6161-b7db-e4a5-3da4-f80e6282cafb"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("9a7b6e52-3e36-4d92-8d1f-4b8a8f80e2ff"),
                            Color = "#66BB6A",
                            Icon = "salary",
                            Name = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9a7b6e52-3e36-4d92-8d1f-4b8a8f800001"),
                            Color = "#81C784",
                            Icon = "money",
                            Name = "Base Pay",
                            ParentId = new Guid("9a7b6e52-3e36-4d92-8d1f-4b8a8f80e2ff"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9a7b6e52-3e36-4d92-8d1f-4b8a8f800002"),
                            Color = "#FFD54F",
                            Icon = "star",
                            Name = "Bonus",
                            ParentId = new Guid("9a7b6e52-3e36-4d92-8d1f-4b8a8f80e2ff"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fc4c7272-c8ec-f5b6-4eb5-09100393db0c"),
                            Color = "#29B6F6",
                            Icon = "laptop",
                            Name = "Freelance",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fc4c7272-c8ec-f5b6-4eb5-091003930001"),
                            Color = "#4FC3F7",
                            Icon = "brief",
                            Name = "Consulting",
                            ParentId = new Guid("fc4c7272-c8ec-f5b6-4eb5-09100393db0c"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fc4c7272-c8ec-f5b6-4eb5-091003930002"),
                            Color = "#81D4FA",
                            Icon = "code",
                            Name = "Side Projects",
                            ParentId = new Guid("fc4c7272-c8ec-f5b6-4eb5-09100393db0c"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0d5d8383-d9fd-06c7-5fc6-1a2114a4ec1d"),
                            Color = "#FFA726",
                            Icon = "chart",
                            Name = "Investments",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0d5d8383-d9fd-06c7-5fc6-1a2114a40001"),
                            Color = "#FFB74D",
                            Icon = "coin",
                            Name = "Dividends",
                            ParentId = new Guid("0d5d8383-d9fd-06c7-5fc6-1a2114a4ec1d"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0d5d8383-d9fd-06c7-5fc6-1a2114a40002"),
                            Color = "#FFCC80",
                            Icon = "percent",
                            Name = "Interest",
                            ParentId = new Guid("0d5d8383-d9fd-06c7-5fc6-1a2114a4ec1d"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OriginalTransactionId");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TargetAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.TransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PromotionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Category", b =>
                {
                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", b =>
                {
                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Account", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.TransactionItem", b =>
                {
                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
