// <auto-generated />
using System;
using FlametteMoney.Web.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlametteMoney.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Color = "#FF7043",
                            Icon = "food",
                            Name = "Food",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c539d706-7a0d-4b5a-9a2c-8f2b4eaa9c2c"),
                            Color = "#FFA726",
                            Icon = "cart",
                            Name = "Groceries",
                            ParentId = new Guid("a1f1c7c7-1d3a-4a0b-930a-5e64c8b6f0b1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7e2b4d17-5b3e-4fd9-a565-0f72a1d39fb1"),
                            Color = "#8D6E63",
                            Icon = "home",
                            Name = "Housing",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2db7b5d4-6ef2-4b64-9f9e-7a5b6d0b1885"),
                            Color = "#42A5F5",
                            Icon = "car",
                            Name = "Transport",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("9a7b6e52-3e36-4d92-8d1f-4b8a8f80e2ff"),
                            Color = "#66BB6A",
                            Icon = "salary",
                            Name = "Salary",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OriginalTransactionId");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TargetAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Category", b =>
                {
                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", b =>
                {
                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Category", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlametteMoney.Web.Infrastructure.Database.Models.Account", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FlametteMoney.Web.Infrastructure.Database.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
