/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsPortfolioRouteImport } from './routes/analytics.portfolio'
import { Route as AnalyticsComparisonRouteImport } from './routes/analytics.comparison'
import { Route as AnalyticsCategoriesRouteImport } from './routes/analytics.categories'
import { Route as AnalyticsCashflowRouteImport } from './routes/analytics.cashflow'
import { Route as ApiSeedDemoRouteImport } from './routes/api/seed/demo'
import { Route as ApiReceiptsScanRouteImport } from './routes/api/receipts/scan'
import { Route as ApiProfileImportBackupRouteImport } from './routes/api/profile/import-backup'
import { Route as ApiProfileExportBackupRouteImport } from './routes/api/profile/export-backup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPortfolioRoute = AnalyticsPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsComparisonRoute = AnalyticsComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsCategoriesRoute = AnalyticsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsCashflowRoute = AnalyticsCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AnalyticsRoute,
} as any)
const ApiSeedDemoRoute = ApiSeedDemoRouteImport.update({
  id: '/api/seed/demo',
  path: '/api/seed/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsScanRoute = ApiReceiptsScanRouteImport.update({
  id: '/api/receipts/scan',
  path: '/api/receipts/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileImportBackupRoute = ApiProfileImportBackupRouteImport.update({
  id: '/api/profile/import-backup',
  path: '/api/profile/import-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileExportBackupRoute = ApiProfileExportBackupRouteImport.update({
  id: '/api/profile/export-backup',
  path: '/api/profile/export-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trips': typeof TripsRoute
  '/analytics/cashflow': typeof AnalyticsCashflowRoute
  '/analytics/categories': typeof AnalyticsCategoriesRoute
  '/analytics/comparison': typeof AnalyticsComparisonRoute
  '/analytics/portfolio': typeof AnalyticsPortfolioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profile/export-backup': typeof ApiProfileExportBackupRoute
  '/api/profile/import-backup': typeof ApiProfileImportBackupRoute
  '/api/receipts/scan': typeof ApiReceiptsScanRoute
  '/api/seed/demo': typeof ApiSeedDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trips': typeof TripsRoute
  '/analytics/cashflow': typeof AnalyticsCashflowRoute
  '/analytics/categories': typeof AnalyticsCategoriesRoute
  '/analytics/comparison': typeof AnalyticsComparisonRoute
  '/analytics/portfolio': typeof AnalyticsPortfolioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profile/export-backup': typeof ApiProfileExportBackupRoute
  '/api/profile/import-backup': typeof ApiProfileImportBackupRoute
  '/api/receipts/scan': typeof ApiReceiptsScanRoute
  '/api/seed/demo': typeof ApiSeedDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trips': typeof TripsRoute
  '/analytics/cashflow': typeof AnalyticsCashflowRoute
  '/analytics/categories': typeof AnalyticsCategoriesRoute
  '/analytics/comparison': typeof AnalyticsComparisonRoute
  '/analytics/portfolio': typeof AnalyticsPortfolioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profile/export-backup': typeof ApiProfileExportBackupRoute
  '/api/profile/import-backup': typeof ApiProfileImportBackupRoute
  '/api/receipts/scan': typeof ApiReceiptsScanRoute
  '/api/seed/demo': typeof ApiSeedDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/categories'
    | '/settings'
    | '/transactions'
    | '/trips'
    | '/analytics/cashflow'
    | '/analytics/categories'
    | '/analytics/comparison'
    | '/analytics/portfolio'
    | '/api/auth/$'
    | '/api/profile/export-backup'
    | '/api/profile/import-backup'
    | '/api/receipts/scan'
    | '/api/seed/demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/categories'
    | '/settings'
    | '/transactions'
    | '/trips'
    | '/analytics/cashflow'
    | '/analytics/categories'
    | '/analytics/comparison'
    | '/analytics/portfolio'
    | '/api/auth/$'
    | '/api/profile/export-backup'
    | '/api/profile/import-backup'
    | '/api/receipts/scan'
    | '/api/seed/demo'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/analytics'
    | '/categories'
    | '/settings'
    | '/transactions'
    | '/trips'
    | '/analytics/cashflow'
    | '/analytics/categories'
    | '/analytics/comparison'
    | '/analytics/portfolio'
    | '/api/auth/$'
    | '/api/profile/export-backup'
    | '/api/profile/import-backup'
    | '/api/receipts/scan'
    | '/api/seed/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  TripsRoute: typeof TripsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProfileExportBackupRoute: typeof ApiProfileExportBackupRoute
  ApiProfileImportBackupRoute: typeof ApiProfileImportBackupRoute
  ApiReceiptsScanRoute: typeof ApiReceiptsScanRoute
  ApiSeedDemoRoute: typeof ApiSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/portfolio': {
      id: '/analytics/portfolio'
      path: '/portfolio'
      fullPath: '/analytics/portfolio'
      preLoaderRoute: typeof AnalyticsPortfolioRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/comparison': {
      id: '/analytics/comparison'
      path: '/comparison'
      fullPath: '/analytics/comparison'
      preLoaderRoute: typeof AnalyticsComparisonRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/categories': {
      id: '/analytics/categories'
      path: '/categories'
      fullPath: '/analytics/categories'
      preLoaderRoute: typeof AnalyticsCategoriesRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/cashflow': {
      id: '/analytics/cashflow'
      path: '/cashflow'
      fullPath: '/analytics/cashflow'
      preLoaderRoute: typeof AnalyticsCashflowRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/api/seed/demo': {
      id: '/api/seed/demo'
      path: '/api/seed/demo'
      fullPath: '/api/seed/demo'
      preLoaderRoute: typeof ApiSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/scan': {
      id: '/api/receipts/scan'
      path: '/api/receipts/scan'
      fullPath: '/api/receipts/scan'
      preLoaderRoute: typeof ApiReceiptsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/import-backup': {
      id: '/api/profile/import-backup'
      path: '/api/profile/import-backup'
      fullPath: '/api/profile/import-backup'
      preLoaderRoute: typeof ApiProfileImportBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/export-backup': {
      id: '/api/profile/export-backup'
      path: '/api/profile/export-backup'
      fullPath: '/api/profile/export-backup'
      preLoaderRoute: typeof ApiProfileExportBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsCashflowRoute: typeof AnalyticsCashflowRoute
  AnalyticsCategoriesRoute: typeof AnalyticsCategoriesRoute
  AnalyticsComparisonRoute: typeof AnalyticsComparisonRoute
  AnalyticsPortfolioRoute: typeof AnalyticsPortfolioRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsCashflowRoute: AnalyticsCashflowRoute,
  AnalyticsCategoriesRoute: AnalyticsCategoriesRoute,
  AnalyticsComparisonRoute: AnalyticsComparisonRoute,
  AnalyticsPortfolioRoute: AnalyticsPortfolioRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  TripsRoute: TripsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProfileExportBackupRoute: ApiProfileExportBackupRoute,
  ApiProfileImportBackupRoute: ApiProfileImportBackupRoute,
  ApiReceiptsScanRoute: ApiReceiptsScanRoute,
  ApiSeedDemoRoute: ApiSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
